-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:6a373ea7d486384dfc39108a55eb0559$
-- 

return {
	texture = 'texturepack1.png',
	frames = {
			{
				name = "cathead",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.0078125, v0 = 0.0078125, u1 = 0.507812, v1 = 0.507812 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "one",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 58 },
				uvRect = { u0 = 0.0078125, v0 = 0.773438, u1 = 0.234375, v1 = 0.890625 },
				spriteSourceSize = { width = 30, height = 58 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "two",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 64 },
				uvRect = { u0 = 0.0078125, v0 = 0.515625, u1 = 0.1875, v1 = 0.765625 },
				spriteSourceSize = { width = 46, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

