-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:fd5127dc2ec68f3dfe02a3a6eeac20ab$
-- 

return {
	texture = 'tp_image.png',
	frames = {
			{
				name = "checkbox_bg.png",
				spriteColorRect = { x = 4, y = 4, width = 34, height = 34 },
				uvRect = { u0 = 0.390625, v0 = 0.242188, u1 = 0.65625, v1 = 0.375 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "checkbox_mark.png",
				spriteColorRect = { x = 1, y = 2, width = 46, height = 34 },
				uvRect = { u0 = 0.015625, v0 = 0.242188, u1 = 0.375, v1 = 0.375 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "gb-down.png",
				spriteColorRect = { x = 3, y = 4, width = 32, height = 32 },
				uvRect = { u0 = 0.671875, v0 = 0.375, u1 = 0.921875, v1 = 0.5 },
				spriteSourceSize = { width = 38, height = 38 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "gb-up.png",
				spriteColorRect = { x = 3, y = 4, width = 32, height = 32 },
				uvRect = { u0 = 0.671875, v0 = 0.242188, u1 = 0.921875, v1 = 0.367188 },
				spriteSourceSize = { width = 38, height = 38 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sz_down.png",
				spriteColorRect = { x = 1, y = 4, width = 60, height = 58 },
				uvRect = { u0 = 0.5, v0 = 0.0078125, u1 = 0.96875, v1 = 0.234375 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sz_up.png",
				spriteColorRect = { x = 1, y = 4, width = 60, height = 58 },
				uvRect = { u0 = 0.015625, v0 = 0.0078125, u1 = 0.484375, v1 = 0.234375 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

