return {
    {title = "Flower Image", scene = "samples/flower_image_sample"},
    {title = "Flower SheetImage", scene = "samples/flower_sheetimage_sample", openAnime = "crossFade", closeAnime = "crossFade"},
    {title = "Flower MovieClip", scene = "samples/flower_movieclip_sample", openAnime = "popIn", closeAnime = "popOut"},
    {title = "Flower MapImage", scene = "samples/flower_mapimage_sample", openAnime = "slideLeft", closeAnime = "slideRight"},
    {title = "Flower NineImage", scene = "samples/flower_nineimage_sample", openAnime = "slideLeft", closeAnime = "slideRight"},
    {title = "Flower Label", scene = "samples/flower_label_sample", openAnime = "slideRight", closeAnime = "slideLeft"},
    {title = "Flower Group", scene = "samples/flower_group_sample", openAnime = "slideRight", closeAnime = "slideLeft"},
    {title = "Flower Graphics", scene = "samples/flower_graphics_sample", openAnime = "slideRight", closeAnime = "slideLeft"},
    {title = "Flower Scene", scene = "samples/flower_scene_sample", openAnime = "slideTop", closeAnime = "slideBottom"},
    {title = "Flower Touch", scene = "samples/flower_touch_sample", openAnime = "slideBottom", closeAnime = "slideTop"},
    {title = "Flower Input", scene = "samples/flower_input_sample", openAnime = "change", closeAnime = "change"},
    {title = "Flower Animation", scene = "samples/flower_animation_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Flower Interceptor", scene = "samples/flower_interceptor_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Tiled Basic 1", scene = "samples/tiled_basic_1_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Tiled Basic 2", scene = "samples/tiled_basic_2_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Tiled Isometric 1", scene = "samples/tiled_iso_1_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Tiled Map Editor", scene = "samples/tiled_map_editor_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Tiled RPG 1", scene = "samples/tiled_rpg_1_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Dungeon 1", scene = "samples/dungeon_1_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Dungeon 2", scene = "samples/dungeon_2_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Dungeon 3", scene = "samples/dungeon_3_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget Button", scene = "samples/widget_button_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget Joystick", scene = "samples/widget_joystick_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget Panel", scene = "samples/widget_panel_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget TextLabel", scene = "samples/widget_textlabel_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget TextBox", scene = "samples/widget_textbox_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget TextInput", scene = "samples/widget_textinput_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget MsgBox", scene = "samples/widget_msgbox_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget DialogBox", scene = "samples/widget_dialogbox_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget ListBox", scene = "samples/widget_listbox_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget Layout", scene = "samples/widget_layout_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget ViewGroup", scene = "samples/widget_viewgroup_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget ScrollGroup", scene = "samples/widget_scrollgroup_sample", openAnime = "slideLeft", closeAnime = "fade"},
    {title = "Widget ScrollView 1", scene = "samples/widget_scrollview_1_sample", openAnime = "slideRight", closeAnime = "fade"},
    {title = "Widget ScrollView 2", scene = "samples/widget_scrollview_2_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget PanelView", scene = "samples/widget_panelview_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Widget TextView", scene = "samples/widget_textview_sample", openAnime = "popIn", closeAnime = "popOut"},
    {title = "Widget ListView", scene = "samples/widget_listview_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Particles", scene = "samples/particles_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Audio", scene = "samples/audio_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Performance Test1", scene = "samples/performance1_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Performance Test2", scene = "samples/performance2_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Spine Skeletal Animation", scene = "samples/spine_boy_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Spine Atlas", scene = "samples/spine_boy_atlas_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Spine Skins", scene = "samples/spine_goblins_sample", openAnime = "fade", closeAnime = "fade"},
    {title = "Task Library", scene = "samples/tasker_sample", openAnime = "fade", closeAnime = "fade"},
}
